services:
     sdzblog.beta_listener:
        class: Sdz\BlogBundle\Beta\BetaListener
        arguments: ["2016-10-29"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
#    sdz_blog.example:
#        class: Sdz\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
